apiVersion: postgresql.kubed.io/v1alpha1
kind: Server
metadata:
  name: psql-main
spec:
  host: postgresql.data.svc.cluster.local
  port: 5432
  sslmode: disable
  credentialsRef:
    namespace: data
    name: psql-main-creds

  purge: true

  # static roles always provisioned regardless of entry labels
  roles:
  - name: test

  # opt LDAP entries in by labeling them:
  # postgresql.kubed.io/server.psql-main: "true"
  entrySelector:
    matchLabels:
      postgresql.kubed.io/server.psql-main: "true"
